application:
    setting:
        proxy-server:
            instance-list:
            - bind-host: 0.0.0.0
              bind-port: 44381
              server-host: 127.0.0.1
              server-port: 44382
              security: vXAZJmQdgXrgkE72anmldRRf8Tue6seDg62jp/VR9SA=
